services:
  radio-bot:
    build:
      context: .
    image: discord-24-7-radio-bot:local
    container_name: discord-radio-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RADIO_URL=${RADIO_URL}
    restart: unless-stopped
    init: true
