services:
  radio-bot:
    image: ghcr.io/wildzun/discord-24-7-radio-bot:master
    container_name: discord-radio-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RADIO_URL=${RADIO_URL}
    restart: unless-stopped
    init: true
